spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxidi
    username: ironhacker
    password: 1r0nh4ck3r2022!*Blu
  jpa:
    show-sql: true # show the commands that are being executed
    #    generate-ddl : true
    hibernate:
      ddl-auto: create # create, create-drop, validate, none, update ....

  profiles:
    active: demo

  server:
    port: 9091 #configuración del puerto donde esta "running"
