
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxidi
    username: ironhacker
    password: 1r0nh4ck3r
  jpa:
    show-sql: true # show the commands that are being executed
    #   generate-ddl : true
    hibernate:
      ddl-auto: create # create, create-drop, validate, none, update ....

  profiles:
    active: demo

amadeus:
  oauth:
    #client_id: ${AMADEUS.CLIENT.ID}
    #client_secret: ${AMADEUS.CLIENT.SECRET}
    client_id: Uot14gEXALZgcN3Bg95FW6YeIAGIfoD7
    client_secret: 4xI9Gcf0U7SlfXIM